# Generated by Django 3.2.6 on 2023-04-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributor_management', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contributor_management.contributor'),
            preserve_default=False,
        ),
    ]
