# Generated by Django 3.2.6 on 2023-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230729_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_type',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
